using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RFSModel
{
   public class CorporateGovAM
    {
        public int CorporateGovAMPK { get; set; }
        public int HistoryPK { get; set; }
        public int Status { get; set; }
        public string Notes { get; set; }
        public string StatusDesc { get; set; }
        public string Date { get; set; }
        public string Row1 { get; set; }
        public string Row2 { get; set; }
        public string Row3 { get; set; }
        public string Row4 { get; set; }
        public string Row5 { get; set; }
        public string Row6 { get; set; }
        public string Row7 { get; set; }
        public string Row8 { get; set; }
        public string Row9 { get; set; }
        public string Row10 { get; set; }
        public string Row11 { get; set; }
        public string Row12 { get; set; }
        public string Row13 { get; set; }
        public string Row14 { get; set; }
        public string Row15 { get; set; }
        public string Row16 { get; set; }
        public string Row17 { get; set; }
        public string Row18 { get; set; }
        public string Row19 { get; set; }
        public string Row20 { get; set; }
        public string Row21 { get; set; }
        public string Row22 { get; set; }
        public string Row23 { get; set; }
        public string Row24 { get; set; }
        public string Row25 { get; set; }
        public string Row26 { get; set; }
        public string Row27 { get; set; }
        public string Row28 { get; set; }
        public string Row29 { get; set; }
        public string Row30 { get; set; }
        public string Row31 { get; set; }
        public string Row32 { get; set; }
        public string Row33 { get; set; }
        public string Row34 { get; set; }
        public string Row35 { get; set; }
        public string Row36 { get; set; }
        public string Row37 { get; set; }
        public string Row38 { get; set; }
        public string Row39 { get; set; }
        public string Row40 { get; set; }
        public string Row41 { get; set; }
        public string Row42 { get; set; }
        public string Row43 { get; set; }
        public string Row44 { get; set; }
        public string Row45 { get; set; }
        public string Row46 { get; set; }
        public string Row47 { get; set; }
        public string Row48 { get; set; }
        public string Row49 { get; set; }
        public string Row50 { get; set; }
        public string Row51 { get; set; }
        public string Row52 { get; set; }
        public string Row53 { get; set; }
        public string Row54 { get; set; }
        public string Row55 { get; set; }
        public string Row56 { get; set; }
        public string Row57 { get; set; }
        public string Row58 { get; set; }
        public string Row59 { get; set; }
        public string Row60 { get; set; }
        public string Row61 { get; set; }
        public string Row62 { get; set; }
        public string Row63 { get; set; }
        public string Row64 { get; set; }
        public string Row65 { get; set; }
        public string Row66 { get; set; }
        public string Row67 { get; set; }
        public string Row68 { get; set; }
        public string Row69 { get; set; }
        public string Row70 { get; set; }
        public string Row71 { get; set; }
        public string Row72 { get; set; }
        public string Row73 { get; set; }
        public string Row74 { get; set; }
        public string Row75 { get; set; }
        public string Row76 { get; set; }
        public string Row77 { get; set; }
        public string Row78 { get; set; }
        public string Row79 { get; set; }
        public string Row80 { get; set; }
        public string Row81 { get; set; }
        public string Row82 { get; set; }
        public string Row83 { get; set; }
        public string Row84 { get; set; }
        public string Row85 { get; set; }
        public string Row86 { get; set; }
        public string Row87 { get; set; }
        public string Row88 { get; set; }
        public string Row89 { get; set; }
        public string Row90 { get; set; }
        public string Row91 { get; set; }
        public string Row92 { get; set; }
        public string Row93 { get; set; }
        public string Row94 { get; set; }
        public string Row95 { get; set; }
        public string Row96 { get; set; }
        public string Row97 { get; set; }
        public string Row98 { get; set; }
        public string Row99 { get; set; }
        public string Row100 { get; set; }
        public string Row101 { get; set; }
        public string Row102 { get; set; }
        public string Row103 { get; set; }
        public string Row104 { get; set; }
        public string Row105 { get; set; }
        public string Row106 { get; set; }
        public string Row107 { get; set; }
        public string Row108 { get; set; }
        public string Row109 { get; set; }
        public string Row110 { get; set; }
        public string Row111 { get; set; }
        public string Row112 { get; set; }
        public string Row113 { get; set; }
        public string Row114 { get; set; }
        public string Row115 { get; set; }
        public string Row116 { get; set; }
        public string Row117 { get; set; }
        public string Row118 { get; set; }
        public string Row119 { get; set; }
        public string Row120 { get; set; }
        public string Row121 { get; set; }
        public string Row122 { get; set; }
        public string Row123 { get; set; }
        public string Row124 { get; set; }
        public string Row125 { get; set; }
        public string Row126 { get; set; }
        public string Row127 { get; set; }
        public string Row128 { get; set; }
        public string Row129 { get; set; }
        public string Row130 { get; set; }
        public string Row131 { get; set; }
        public string Row132 { get; set; }
        public string Row133 { get; set; }
        public string Row134 { get; set; }
        public string Row135 { get; set; }
        public string Row136 { get; set; }
        public string Row137 { get; set; }
        public string Row138 { get; set; }
        public string Row139 { get; set; }
        public string Row140 { get; set; }
        public string Row141 { get; set; }
        public string Row142 { get; set; }
        public string Row143 { get; set; }
        public string Row144 { get; set; }
        public string Row145 { get; set; }
        public string Row146 { get; set; }
        public string Row147 { get; set; }
        public string Row148 { get; set; }
        public string Row149 { get; set; }
        public string Row150 { get; set; }
        public string Row151 { get; set; }
        public string Row152 { get; set; }
        public string Row153 { get; set; }
        public string Row154 { get; set; }
        public string Row155 { get; set; }
        public string Row156 { get; set; }
        public string Row157 { get; set; }
        public string Row158 { get; set; }
        public string Row159 { get; set; }
        public string Row160 { get; set; }
        public string Row161 { get; set; }
        public string Row162 { get; set; }
        public string Row163 { get; set; }
        public string Row164 { get; set; }
        public string Row165 { get; set; }
        public string Row166 { get; set; }
        public string Row167 { get; set; }
        public string Row168 { get; set; }
        public string Row169 { get; set; }
        public string Row170 { get; set; }
        public string Row171 { get; set; }
        public string Row172 { get; set; }
        public string Row173 { get; set; }
        public string Row174 { get; set; }
        public string Row175 { get; set; }
        public string Row176 { get; set; }
        public string Row177 { get; set; }
        public string Row178 { get; set; }
        public string Row179 { get; set; }
        public string Row180 { get; set; }
        public string Row181 { get; set; }
        public string Row182 { get; set; }
        public string Row183 { get; set; }
        public string Row184 { get; set; }
        public string Row185 { get; set; }
        public string Row186 { get; set; }
        public string Row187 { get; set; }
        public string Row188 { get; set; }
        public string Row189 { get; set; }
        public string Row190 { get; set; }
        public string Row191 { get; set; }
        public string Row192 { get; set; }
        public string Row193 { get; set; }
        public string Row194 { get; set; }
        public string Row195 { get; set; }
        public string Row196 { get; set; }
        public string Row197 { get; set; }
        public string Row198 { get; set; }
        public string Row199 { get; set; }
        public string Row200 { get; set; }
        public string Row201 { get; set; }
        public string Row202 { get; set; }
        public string Row203 { get; set; }
        public string Row204 { get; set; }
        public string Row205 { get; set; }
        public string Row206 { get; set; }
        public string Row207 { get; set; }
        public string Row208 { get; set; }
        public string Row209 { get; set; }
        public string Row210 { get; set; }
        public string Row211 { get; set; }
        public string Row212 { get; set; }
        public string Row213 { get; set; }
        public string Row214 { get; set; }
        public string Row215 { get; set; }
        public string Row216 { get; set; }
        public string Row217 { get; set; }
        public string Row218 { get; set; }
        public string Row219 { get; set; }
        public string Row220 { get; set; }
        public string Row221 { get; set; }
        public string Row222 { get; set; }
        public string Row223 { get; set; }
        public string Row224 { get; set; }
        public string Row225 { get; set; }
        public string Row226 { get; set; }
        public string Row227 { get; set; }
        public string Row228 { get; set; }
        public string Row229 { get; set; }
        public string Row230 { get; set; }
        public string Row231 { get; set; }
        public string Row232 { get; set; }
        public string Row233 { get; set; }
        public string Row234 { get; set; }
        public string Row235 { get; set; }
        public string Row236 { get; set; }
        public string Row237 { get; set; }
        public string Row238 { get; set; }
        public string Row239 { get; set; }
        public string Row240 { get; set; }
        public string Row241 { get; set; }
        public string Row242 { get; set; }
        public string Row243 { get; set; }
        public string Row244 { get; set; }
        public string Row245 { get; set; }
        public string Row246 { get; set; }
        public string Row247 { get; set; }
        public string Row248 { get; set; }
        public string Row249 { get; set; }
        public string Row250 { get; set; }
        public string Row251 { get; set; }
        public string EntryUsersID { get; set; }
        public string EntryTime { get; set; }
        public string UpdateUsersID { get; set; }
        public string UpdateTime { get; set; }
        public string ApprovedUsersID { get; set; }
        public string ApprovedTime { get; set; }
        public string VoidUsersID { get; set; }
        public string VoidTime { get; set; }
        public string DBUserID { get; set; }
        public string DBTerminalID { get; set; }
        public string LastUpdate { get; set; }
        public string LastUpdateDB { get; set; }

    }
}
